version: 0.0
os: linux

files:
  - source: / # Adjust this to point to your actual source directory
    destination: /var/www/html/build

permissions:
  - object: /var/www/html/build  # This is more specific than "/" to avoid potential issues
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      # runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      # runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      # runas: root
